#!/usr/bin/env bash
## -*- mode: sh-mode; coding: utf-8 -*-

#
# Paths
#

# export PATH=/usr/local/bin:$PATH

# dotfiles
export DOTFILES_ROOT=$HOME/dotfiles
export PATH=$DOTFILES_ROOT/bin:$DOTFILES_ROOT/local/bin:$PATH

#
# Emacs
#

export EMACS_HOME=$HOME/.emacs.d
export PATH=$EMACS_HOME/bin:$EMACS_HOME/site-bin:$PATH

export LSP_USE_PLISTS=true      # lsp-mode
