#!/usr/bin/env bash
## -*- mode: sh-mode; coding: utf-8 -*-

#
# Paths
#

# export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH


# dotfiles
export DOTFILES_ROOT=$HOME/dotfiles
export PATH=$DOTFILES_ROOT/bin:$DOTFILES_ROOT/local/bin:$PATH

# Display current directory in terminal tab/title
# shellcheck disable=SC2016
PROMPT_COMMAND+=('echo -ne "\033]0;${PWD##*/}\007"')

#
# Emacs
#

export EMACS_HOME=$HOME/.emacs.d
export PATH=$EMACS_HOME/bin:$EMACS_HOME/site-bin:$PATH

export EDITOR="emacsclient -c"
export LSP_USE_PLISTS=true      # lsp-mode
