brew "coreutils" if OS.mac?
brew "mas" if OS.mac?
brew "git" if OS.mac?
brew "gnu-sed" if OS.mac?
brew "wget" if OS.mac?
brew "tree" if OS.mac?
brew "gcc" if OS.linux?
brew "gh"
brew "direnv"
brew "ripgrep"
brew "jq"
brew "yq"
brew "asdf"
brew "fnm"
brew "nkf"
brew "shellcheck"
brew "csvq"
brew "csvtk"

tap "noborus/tap"
brew "noborus/tap/trdsql"

tap "heroku/brew" if OS.mac?
brew "heroku" if OS.mac?
